### ISSUE TITLE
Can't introduce my credentials, stuck in "Authenticating...."

### ISSUE THREAD

**Issue by PedroS11** [icloud-photos-downloader/icloud_photos_downloader#1104]
## Overview
I'm running this repo with docker-compose on a mac, but the terminal gets stuck in the "Authenticating..." message and I can't input my credentials to login. Am I missing something? Tried to search for similar issues here but nothing that helped me

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. Version of the app, OS/System, and minimum command line to reproduce. )

my docker-compose.yaml file
```
version: "3"

services:
  icloud-downloader:
    stdin_open: true
    tty: true
    container_name: icloud-downloader
    volumes:
      - ${PWD}/Photos:/data
    environment:
      - TZ=Europe/London
    image: icloudpd/icloudpd:latest
    command: icloudpd --directory /data --username MY_EMAIL@gmail.com --auth-only --mfa-provider console
```

My foder structure (the Photos folder is empty)

<img width="257" alt="Image" src="https://github.com/user-attachments/assets/b2f741e1-fb6e-49e1-9e07-707f280d93dd" />

1. docker compose up

## Expected Behavior
A prompt to ask for credentials

## Actual Behavior
Stuck in Authenticating message

<img width="551" alt="Image" src="https://github.com/user-attachments/assets/16cdf498-6341-4eda-8d3d-4f20ef4f9b4e" />
