### ISSUE TITLE
List-Libraries only shows libraries for which the iCloud account is the primary owner

### ISSUE THREAD

**Issue by SamTheGeek** [icloud-photos-downloader/icloud_photos_downloader#947]
## Overview
When using `--list-libraries` to show available libraries, my list only shows `PrimarySync`. However, I am also a participant in (but not the owner of) a Shared Library that displays in my iCloud account. `--list-libraries` (and the `-library` command) should show both libraries.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Accept an invitation to an iCloud Shared Photo Library owned by another account
2. Run `--list-libraries`

## Expected Behavior
Both the primary and shared library would be listed

## Actual Behavior
Only the primary library is listed

**Comment by boredazfcuk** [comment]
> Only the primary library is listed

This is expected behaviour. 

Apple does not provide the capability to access shared libraries that you are only a participant of, only ones that you are an owner of.

Or at least this was my understanding from when shared libraries were originally released. I guess they may have changed recently. You can check by logging into icloud.com. You can only download from albums/libraries you find in there.

**Comment by SamTheGeek** [comment]
You have been able to access shared libraries on the web since at least last fall. Here's what I see when logging in to iCloud.com and selecting photos.
<img width="286" alt="Screenshot of iCloud.com" src="https://github.com/user-attachments/assets/aaac6523-ae22-4b7e-841a-89be12c495d1">

**Comment by AndreyNikiforov** [comment]
Can you try to list libraries by icloudpd, pls? That should confirm if we are indeed reading them from icloud.com or not

```shell
docker run --rm -it icloudpd/icloudpd:1.23.4 icloudpd -u your@email.address -d . --list-libraries
```

**Comment by AndreyNikiforov** [comment]
> > Only the primary library is listed
> 
> This is expected behaviour.
> 
> Apple does not provide the capability to access shared libraries that you are only a participant of, only ones that you are an owner of.
> 
> Or at least this was my understanding from when shared libraries were originally released. I guess they may have changed recently. You can check by logging into icloud.com. You can only download from albums/libraries you find in there.

IIUC browsing (and downloading) assets from Shared library [should be possible](https://support.apple.com/en-us/118229)

**Comment by boredazfcuk** [comment]
Shared libraries are created with end-to-end encryption using ADP if the library owner has it enabled for their account. Maybe this is why users cannot see the shared libraries that they are only members of... the owners have ADP enabled.

**Comment by SamTheGeek** [comment]
@AndreyNikiforov output of `--list-libraries`

> `2024-09-05 15:27:40 DEBUG    Authenticating...`
`PrimarySync`

The main user does not have ADP on (nor knows what that is) and I don't either.

**Comment by AndreyNikiforov** [comment]
> @AndreyNikiforov output of `--list-libraries`
> 
> > `2024-09-05 15:27:40 DEBUG    Authenticating...`
> > `PrimarySync`
> 
> The main user does not have ADP on (nor knows what that is) and I don't either.

To summarize, when opening icloud.com in the browser, you can see Personal and Shared libs, while `icloudpd` for the same account shows only Personal (==PrimarySync, IIUC). Interesting...

**Comment by SamTheGeek** [comment]
Exactly so. Fascinating indeed!

**Comment by spiderpug** [comment]
I'm also in this situation and I would like to sync/download photos of the Shared Library primarily.

Is there anything I can do to help debugging or solving this?

**Comment by mitchplze** [comment]
From the command line, I am able to list my Personal Library name, and then my wife and I's "Shared Library". 
I am the 'owner' of said library, and my iCloud does all the heavy lifting.

````
SharedSync-EBC80CC8-EFA3-44C9-88A5-XYXYZZZZABCD
PrimarySync
````
_(UID of the shared library is redacted/altered here)_

Due to the limitation mentioned (only one library can be used by icloudpd), I simply created a new Docker stack with alternate settings, and run it in parallel with a different port, different volumes, and the command line switch.

### Personal Library

````
services:
  icloudpd:
    stdin_open: true
    tty: true
    volumes:
      - photos:/data
      - cookies:/cookies
      - scripts:/scripts
    environment:
      - TZ=America/Vancouver
    ports:
      - 5555:8080
    image: icloudpd/icloudpd:latest

    command: >
      icloudpd 
      --directory /data 
      --cookie-directory /cookies
      --username <redacted>
      --watch-with-interval 3600 
      --password-provider webui
      --mfa-provider webui 
      --set-exif-datetime
      --auto-delete 


volumes:
  photos:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/homes/mitch/Photos    
  cookies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/docker/icloudpd-mitch/cookies            
  scripts:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/docker/icloudpd-mitch/scripts  
````

### Shared Library

````
services:
  icloudpd:
    stdin_open: true
    tty: true
    volumes:
      - photos_shared:/data
      - cookies:/cookies
      - scripts:/scripts
    environment:
      - TZ=America/Vancouver
    ports:
      - 5556:8080
    image: icloudpd/icloudpd:latest

    command: >
      icloudpd 
      --directory /data 
      --cookie-directory /cookies
      --username <redacted>
      --watch-with-interval 3600 
      --password-provider webui
      --mfa-provider webui 
      --set-exif-datetime
      --auto-delete 
      --library "SharedSync-EBC80CC8-EF...<redacted>" 

volumes:
  photos_shared:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/homes/mitch/Photos-Shared
  cookies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/docker/icloudpd-shared/cookies            
  scripts:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw 
      device: :/volume1/docker/icloudpd-shared/scripts  
````

This seems to be working flawlessly for me in production.
