### ISSUE TITLE
Docker Compose.yaml

### ISSUE THREAD

**Issue by BulldozerPete** [icloud-photos-downloader/icloud_photos_downloader#969]
## Summary
[NOTE]: Please provide a default Docker Compose.yaml

## Context
[NOTE]: Managing and modifying containers with Docker Compose is much easier.

**Comment by AndreyNikiforov** [comment]
Are you looking for a guidance on how to convert your docker command (e.g. `docker run icloudpd\icloudpd icloudpd --param1 --param2`) into [compose yaml](https://docs.docker.com/compose/intro/compose-application-model/)?

Are you currently using compose? How many services your are running there? What specifics of compose are you expecting to be more valuable that using docker cli for `icloudpd`?

**Comment by BulldozerPete** [comment]
I don't know how to convert.
https://www.composerize.com gave this:

version: "3"
services:
    icloudpd:
        image: icloudpd
        command: --directory /data --username my@email.address --watch-with-interval
            3600


I am running 19 services via docker compose and like to store these "configs" in case of an data loss/ hw issue.

**Comment by BulldozerPete** [comment]
I can't get you app running.

I documentation is described to use this command:

`docker run -it --rm --name icloudpd -v $(pwd)/Photos:/data -e TZ=America/Los_Angeles icloudpd/icloudpd:latest icloudpd --directory /data --username my@email.address --watch-with-interval 3600`

I have composerized your command to this:

```
services:
    icloudpd:
        stdin_open: true
        tty: true
        container_name: icloudpd
        volumes:
            - $(pwd)/Photos:/data
        environment:
            - TZ=America/Los_Angeles
        image: icloudpd/icloudpd:latest
        command: icloudpd --directory /data --username my@email.address
            --watch-with-interval 3600
```

The I have change the volume and timezone.

Now the app is stuck at "Authenticating...".
How do I enter my password?
